---
title: "reburn-mtbs-data-prep"
output: html_document
date: '2022-06-03'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(lubridate)
library(tidyverse)
library(here)
library(rgdal)
library(rgeos)
library(sp)
library(sf)
library(readxl)
library(terra)
library(raster) # for the rasterize function in this package
library(tictoc) # for simple tracking of computation time

data_dir = readLines(here("data_dir.txt"), n=1)
source(here("scripts/convenience_functions.R"))
```

This script creates raster layers to use as fire history explanatory variables in the reburn severity models

--------------------------------------------------------------------------------
## Fire History

Rasterize mtbs for easy extraction
```{r rasterize perims}
# Rasterize mtbs for easy extraction.  - need to use project coordinate system - like Albers equal area conical 
# Equal Area Conus Albers. - epsg:5070. could use UTMs, but would have to change depending on where in the US the data came from.

perims = st_read(datadir("/raw-data/fire-perims/mtbs_perimeter_data/mtbs_west_fs_nps_sub.shp"))

perims = st_transform(perims, 5070)  

r = rast(perims, resolution = 30, crs = "epsg:5070")

```


## Extract data on the most recent and second most recent fires
```{r extract most recent fires}

tic()
mostrecent_fire = raster::rasterize(perims %>% as("Spatial"), r %>% raster(), field="Fire_Year", fun=max)
toc()
#208.07 sec elapsed for z1
#7886.27 sec elapsed
writeRaster(mostrecent_fire, datadir("/prelim-outputs/fire_history/mostrecent_fire_all.tif"), overwrite = TRUE)


#--------------
#function to extract second most recent fire 
second_recent_func = function(x, na.rm) {
  x = x[!is.na(x)]
  if(length(x) == 0) { return(NA) }
  x_nomax = x[x != max(x)]
  if (length(x_nomax) == 0) { return(NA) }
  second_recent =  max(x_nomax)
  return(second_recent)
}

tic()
secondrecent_fire = raster::rasterize(perims %>% as("Spatial"), r %>% raster, field="Fire_Year", fun=second_recent_func)
toc()
#287.91 sec elapsed for z1
#6872.91 sec elapsed for all fires
writeRaster(secondrecent_fire, datadir("/prelim-outputs/fire_history/secondrecent_fire_all.tif"), overwrite = TRUE)

#-------------
#calculate time between most recent and second most recent burns
tic()
time_between_burns <- overlay(mostrecent_fire,
                      secondrecent_fire,
                      fun=function(r1, r2){return(r1-r2)})
toc()
writeRaster(time_between_burns, datadir("/prelim-outputs/fire_history/time_between_burns_all.tif"), overwrite = TRUE)
#658.31 sec elapsed
```

## Calculate the number of times each cell within a fire perimeter has burned


```{r}
perims = st_read(datadir("/raw-data/fire-perims/mtbs_perimeter_data/mtbs_west_fs_nps_sub_updated21.shp"))

perims = st_transform(perims, 5070)  

r = rast(perims, resolution = 30, crs = "epsg:5070")
r = raster(r)

tic()
rast_count = rasterize(perims, r, field = "Fire_Year", fun = "count")
# plot(rast_count)
toc()
writeRaster(rast_count, datadir("/prelim-outputs/fire_history/count_burns.tif"), overwrite = TRUE)

```

---------------------------------------------------------------------


Tried to create reaster for each shapefile and then compile to calculate number of times burned, but ran out of memory, so using approach above. 

Create separate shapefiles for each year
```{r separate shapefiles by year}
# perims_ogr = readOGR(datadir("/raw-data/fire-perims/mtbs_perimeter_data/mtbs_west_fs_nps_sub.shp"))
# 
# perim_yrs = unique(perims_ogr$Fire_Year)
# 
# for(i in 1:length(perim_yrs)) {
#     tmp = perims_ogr[perims_ogr$Fire_Year == perim_yrs[i], ]
#   writeOGR(tmp, dsn=getwd(), perim_yrs[i], driver="ESRI Shapefile",
#            overwrite_layer=TRUE)
#    }
# #read in shape files for each year
# files = list.files(datadir("/raw-data/fire-perims/fire_perims_1985_2021_by_year/"), pattern = "[.]shp$", full.names=T)
# 
# perims_list = lapply(files, readOGR)
# 
# #tranform perims_list to projected coordinate system = epsg:5070
# albrs_crs = crs(perims)
# 
# transform_fun = function(shp){
#   spTransform(shp, albrs_crs)
# }
# 
# perims_list = lapply(perims_list, transform_fun)
# 
# #convert to sf for faster rasterization
# perims_list_sf = lapply(perims_list, st_as_sf)
# 
# #convert r to "RasterLayer"
# r_temp = raster(r)
# 
# ## looping list with fasterize
# library(fasterize)
# 
# x <- list()
# 
#   for(i in 1:2){
#   x[[1]] = rasterize(perims_list_sf[[1]], r_temp)
# } #memory error
# 
# s <- stack(x)
# # plot(s)

```