---
title: "reburn-mtbs-data-prep"
output: html_document
date: '2022-06-03'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(lubridate)
library(tidyverse)
library(here)
library(rgdal)
library(rgeos)
library(sp)
library(sf)
library(readxl)
library(terra)
library(raster) # for the rasterize function in this package
library(tictoc) # for simple tracking of computation time

data_dir = readLines(here("data_dir.txt"), n=1)
source(here("scripts/convenience_functions.R"))

```

This script preps MTBS data for the CA reburn analysis

# Organize MTBS data

load mtbs data

```{r load data}
#load mtbs data
mtbs_perims = vect(datadir("/raw-data/fire-perims/mtbs_perimeter_data/mtbs_perims_DD.shp")) #Mercator (EPSG: 4269)

#add fire year
mtbs_perims$YEAR = as.numeric(substr(as.character(mtbs_perims$Ig_Date), 1,4)) 
#DY: This line isn't necessary since the correct CRS is stored in the shapefile: crs(mtbs_perims) = 'epsg:4269'
```


Prep perims for GEE burn severity extraction and subset by year
```{r gee prep}
#grid out CA and subset
#DY: This tiling approach looks great. We should keep an eye out for possible cases where edge effects might be an issue, and if they exist, add a buffer to the grid.

#rename mtbs cols for GEE - following Parks et al 2019 GEE code for calculating CBI
# //       Fire_ID        unique identifier for each fire
# //       Fire_Year      year of fire
# //       Start_Day      start day of fire season in julian days, e.g. June 15 = 166
# //       End_Day        end day of fire season in julian days

mtbs_perims$Fire_ID = mtbs_perims$Event_ID
mtbs_perims$Fire_Year = as.integer(mtbs_perims$YEAR)

mtbs_perims$Start_Day = yday(mtbs_perims$Ig_Date) #Q: not sure if this should be actual start date or average for CA?
mtbs_perims$End_Day = 273

mtbs_perims = mtbs_perims[,c("Fire_ID", "Fire_Year", "Start_Day", "End_Day")]

#remove fires from before 1986 because we don't have pre-fire imagery
mtbs_perims = mtbs_perims[which(mtbs_perims$Fire_Year > 1985),]
```


bring in 2021 fires >100ac
```{r load 2021 fires}
#load mtbs data
perims21 = vect(datadir("/raw-data/fire-perims/WFIGS-Wildland_Fire_perims_full_history_7_18_22.gdb")) # (EPSG: 4326)

#set crs
crs(perims21) <- crs(mtbs_perims)

#add relevant columns to match mtbs data for gee
perims21$Fire_Year = as.integer(as.numeric(substr(as.character(perims21$irwin_FireDiscoveryDateTime), 1,4))) 
perims21$Fire_ID = perims21$irwin_UniqueFireIdentifier

perims21$Start_Day = yday(perims21$irwin_FireDiscoveryDateTime) #Q: not sure if this should be actual start date or average?
perims21$End_Day = 273 #Q: not sure if this should be containment date (not available in mtbs) or average?

#keep only 2021 fires because these aren't included in mtbs
perims21 = perims21[which(perims21$Fire_Year == 2021),]

#remove fires <1000 ac
perims21 = perims21[which(perims21$irwin_CalculatedAcres >1000),] #area reported in in acres


perims21 = perims21[,c("Fire_ID", "Fire_Year", "Start_Day", "End_Day")]

```

bind mtbs and 2021 IRWIN fire perims >1000 acres
```{r bind perims}
mtbs_perims21 = rbind(mtbs_perims, perims21)

```


### Subset and tile data for faster processing 

Subset by state
```{r subset data  by state}

#extract states of interest
#load state boundaries
states = vect(datadir("/raw-data/geography/cb_2018_us_state_20m/cb_2018_us_state_20m.shp")) 

states = project(states, mtbs_perims21)

west = states[states$NAME == "California" | states$NAME == "Washington" | states$NAME == "Oregon" | states$NAME == "Idaho" | states$NAME == "Colorado" | states$NAME == "Montana" | states$NAME == "Wyoming" | states$NAME == "Utah" | states$NAME == "Nevada" | states$NAME == "Arizona" | states$NAME == "New Mexico",]

#dissolve state boundaries before intersecting 
west_ag = aggregate(west)

#buffer western states 5k
west_buf = buffer(west_ag, 5000)

#crop perims to only include western states
mtbs_west = crop(mtbs_perims21,west_buf)


#reproject to UTMs Zone 10 for units = m
newcrs = "epsg:26910"
mtbs_west = project(mtbs_west, newcrs)
```

Remove fires that didn't burn on FS land
```{r}
#load fs land spatial data
ownership_fs = read_sf(datadir("/raw-data/ownership/S_USA.BasicOwnership.gdb"), "BasicOwnership") %>% rename("UNIT_NAME" = "FORESTNAME",
                                       "OBJECTID" = "BASICOWNERSHIPID") %>%
                subset(OWNERCLASSIFICATION == "USDA FOREST SERVICE") %>%
                dplyr::select(OBJECTID, UNIT_NAME, SHAPE_Area, SHAPE)

#read in nps data
ownership_nps = read_sf(datadir("/raw-data/ownership/nps_boundary/nps_boundary.shp"))

ownership_nps = ownership_nps %>%
                subset(UNIT_TYPE == "National Park") %>%
                mutate(SHAPE = geometry,
                       SHAPE_Area = Shape_Area) %>%
                dplyr::select(OBJECTID, UNIT_NAME, SHAPE_Area) %>%
                rename("SHAPE" = "geometry")


#combine nps and fs data
ownership = rbind(ownership_fs, ownership_nps)

#set crs equal to mtbs layer
ownership = st_transform(ownership, st_crs(mtbs_west))  

#convert mtbs data to sf object for intersection
mtbs_west_sf = sf::st_as_sf(mtbs_west) 

#intersect with mtbs 
mtbs_fs_int = st_intersection(mtbs_west_sf, ownership) #not sure why, but this only runs when crs = "epsg:26910" - UTMs


#subset mtbs_west so that only fires that intersect FS land and NPS are included in severity analysis
mtbs_west_fs_sub = mtbs_west[mtbs_west$Fire_ID %in% mtbs_fs_int$Fire_ID]

#set crs back to NAD83 for GEE
NAD83 = "epsg:4269"
mtbs_west_fs_sub = project(mtbs_west_fs_sub, NAD83)

#save subset mtbs as shapefile
#save mtbs zones as shapefiles
writeVector(mtbs_west_fs_sub, file = datadir("/raw-data/fire-perims/mtbs_perimeter_data/mtbs_west_fs_nps_sub.shp"))

# plot(mtbs_fs_int[1])
# plot(ownership[1], add = T, color = "red")
```


tile perims data for faster processing
```{r tiling}
#larger grid for GEE
z <- rast(mtbs_west_fs_sub)

dim(z) <- c(3,3)
values(z) <- 1:9
names(z) <- 'Zone'
z <- as.polygons(z) # coerce SpatRaster to SpatVector polygons
bz <- buffer(z, width=300) # add 300m buffer around zones

#create a list of zone names
zones <- paste("mtbs_fs_z",1:9, sep = "")
zone_list <- vector(mode="list", length = 9)
names(zone_list) = zones

#create mtbs variable for each zone with 300m buffer
for (i in 1:length(bz)){
  zone_list[[i]] <- terra::intersect(mtbs_west_fs_sub, bz[i,])
}

#remove mtbs zones with no fires leaving 17 zones to run
zone_list <- zone_list[sapply(zone_list, function(x) length(x) > 0)]

#save zones

writeVector(z, file = datadir("/prelim-outputs/analysis_zones9/analysis_zones9.gpkg"))
```

save shapefiles
```{r save shps, eval = FALSE}
#export zone list as R data - Apparently this doesn't work with terra Spat- objects (https://github.com/rspatial/terra/issues/549)
# save(zone_list, file = datadir("/raw-data/fire-perims/mtbs_perimeter_data/mtbs_ca_zones/mtbs_ca_zones.RData"))

#save perims by zones as shapefiles
lapply(1:length(zone_list), function(i) writeVector(zone_list[[i]], file = datadir(paste0("/raw-data/fire-perims/mtbs_perimeter_data/mtbs_fs_zones/", names(zone_list[i]), ".shp")),overwrite = TRUE))

# writeVector(mtbs_ca, file = datadir("/raw-data/fire-perims/mtbs_perimeter_data/mtbs_ca_zones/mtbs_ca.shp"), overwrite = TRUE)
# 
# writeVector(mtbs_west, file = datadir("/raw-data/fire-perims/mtbs_perimeter_data/mtbs_ca_zones/mtbs_west.shp"), overwrite = TRUE)


plot(zone_list[[1]])
```


<!-- ---------------------------------------------------------------------------------------- -->
<!-- # Subset FS land -->

<!-- remove fires that did not burn on FS land (keep perims with >=50 ha overlap) -->
<!-- ```{r FS land, eval = FALSE} -->
<!-- #load ca fs land spatial data -->
<!-- fs = vect(datadir("/raw-data/ownership/fsland_ca.gpkg"))  -->
<!-- # plot(fs) -->
<!-- fs = project(fs, newcrs) #project to UTMs -->

<!-- fs_sf = sf::st_as_sf(fs) -->
<!-- mtbs_ca_sf = sf::st_as_sf(mtbs_ca) -->


<!-- # intersect - note that sf is intelligent with attribute data! -->
<!-- fs_mtbs_int <- st_intersection(mtbs_ca_sf, fs_sf) -->
<!-- # plot(mtbs_ca_sf$geometry, axes = TRUE) -->
<!-- # plot(fs_mtbs_int$geometry, add = TRUE, col = 'red') -->

<!-- # add in areas in m2 -->
<!-- fs_area <- fs_mtbs_int %>%  -->
<!--   mutate(area = st_area(.) %>% as.numeric()) -->

<!-- # for each perim, get area overlap with forest service land, then remove areas with <50 ha overlap -->
<!-- fs_area = fs_area %>%  -->
<!--   as_tibble() %>%  -->
<!--   group_by(Event_ID, OWNERCLASSIFICATION) %>%  -->
<!--   summarize(area = sum(area)) %>% -->
<!--   filter(area >= 500000) -->

<!-- #select fire perims that >= 50ha identified in fs_area -->
<!-- fs_mtbs_ca = mtbs_ca[mtbs_ca$Event_ID %in% fs_area$Event_ID,] -->

<!-- #some summary stats/data vis -->
<!-- # fs_mtbs_ca %>% data.frame() %>%  -->
<!-- #   group_by(YEAR) %>%  -->
<!-- #   summarise(acres_yr = sum(BurnBndAc)) %>%  -->
<!-- #   plot(acres_yr ~ YEAR) -->
<!-- ``` -->
