---
title: "reburn-data-prep"
output: html_document
date: '2022-06-03'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(tidyverse)
library(here)
library(sf)
library(readxl)
library(terra)

data_dir = readLines(here("data_dir.txt"), n=1)
source(here("scripts/convenience_functions.R"))

```

This script preps data for the CA reburn analysis

Read in MTBS fire perims
```{r}
mtbs_perims = vect(datadir("/raw-data/fire-perims/mtbs_perimeter_data/mtbs_perims_DD.shp"))
#add fire year
mtbs_perims$YEAR = as.numeric(substr(as.character(mtbs_perims$Ig_Date), 1,4)) 

# Rasterize it for easy extraction. 
r = rast(mtbs_perims, resolution=50,crs="+proj=aea +lat_1=34 +lat_2=40.5 +lat_0=0 +lon_0=-120 +x_0=0 +y_0=-4000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")

#When two fires overlap, keep the year of the most recent and second most recent
mostrecent_fire = rasterize(mtbs_perims,r, field="Ig_Date", fun=max)

#function to extract second most recent fire 
second_highest_func = function(x) {
  max(x[x != max(x)])    
}

secondrecent_fire = rasterize(mtbs_perims,r, field="Ig_Date", fun=second_highest_func)


## Bring in the important 2021 fires (Caldor and Dixie), rasterize them too

# caldor = vect(datadir("fire-perims/ca3858612053820210815_20201011_20211016_ravg_data/ca3858612053820210815_20201011_20211016/CA3858612053820210815.kml"))
# caldor = project(caldor,r)
# caldor$year = 2021
# caldor_rast = rasterize(caldor,r,field="year", fun=max)
# dixie = vect(datadir("fire-perims/ca3987612137920210714_20201012_20211015_ravg_data/ca3987612137920210714_20201012_20211015/CA3987612137920210714.kml"))
# dixie = project(dixie,r)
# dixie$year = 2021
# dixie_rast = rasterize(dixie,r,field="year", fun=max)

## Stack the fires and get the most recent year of fire for each pixel, accounting for 2021 fires too
# fire_hist = c(mostrecent_fire,caldor_rast,dixie_rast)
# fire_hist = max(fire_hist, na.rm=TRUE)
```

#assign states to perimeters
state_bnds = read_sf(datadir("/geography/cb_2018_us_state_20m/cb_2018_us_state_20m.shp"))
