---
title: "extract-reburn-area"
author: "CT"
date: '2022-07-20'
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(lubridate)
library(tidyverse)
library(here)
library(rgdal)
library(rgeos)
library(geos)
library(sp)
library(sf)
library(readxl)
library(terra)
library(raster) # for the rasterize function in this package
library(tictoc) # for simple tracking of computation time

data_dir = readLines(here("data_dir.txt"), n=1)
source(here("scripts/convenience_functions.R"))

```



This script overlays reburned areas with BPS and FS data layers for decision making

```{r load data}
#load mtbs data
reburn = vect(datadir("/prelim-outputs/reburns/reburn85_21.shp")) 
newcrs =  "EPSG:5070"  
reburn = project(reburn, newcrs) #reproject to match Landfire
```

## Overlay with Landfire BPS to get BPS codes for reburned area

load data
```{r, eval = FALSE}
# #load ca fs land spatial data
# bps = rast(datadir("/raw-data/Landfire/LF2017_BPS_200_WEST/LC16_BPS_200_West.tif")) 
# 
# #mask out non-reburn areas
# bps_reburn = mask(bps, reburn)
# writeRaster(bps_reburn, datadir("/prelim-outputs/bps_reburn_mask.tif")) #save a read back in because masking took so long

#read in bps vector - converted in Arc Pro to save memory
# bps_reburn = vect(datadir("/prelim-outputs/BPS/bps_reburn_vect.shp")) 
```

Read in BPS codes
```{r BPS codes}
bps_codes = read.csv(datadir("/raw-data/Landfire/LF2016_BPS_200_CONUS/CSV_Data/LF16_BPS_200.csv"))

#create new layer with only forested areas. *Note these are areas have the potential to be forested so not necessarily representative of forest at the time of fire
#*For now, only including BS with forest in the name, excluding woodlands
forest_codes = bps_codes %>% filter(grepl('Forest', BPS_NAME))
# 
# forest = subset(bps_reburn, bps_reburn$gridcode %in% forest_codes$VALUE)
# writeVector(forest, datadir("/prelim-outputs/BPS/bps_forest_reburn_mask.shp")) #save a read back in because reading in the entire shp file took so long
```

```{r}
bps_forest = read_sf(datadir("/prelim-outputs/BPS/bps_forest_reburn_mask.shp")) #read_sf is faster than st_read

bps_forest <- bps_forest %>% 
  mutate(area = st_area(.) %>% as.numeric())

forest_df = as.data.frame(bps_forest) %>% 
  rename("VALUE" = gridcode) %>% 
  merge(., forest_codes[,c(1,2,5)], all.y = FALSE) %>% 
  dplyr::select(c(VALUE, BPS_NAME, area)) %>%
  mutate(percArea = as.numeric((area / sum(area)) *100))

plot(forest_df$percArea ~ forest_df$VALUE)

```
## Check to see how much forested reburned area falls in FS land

```{r FS land, eval = FALSE}
#load ca fs land spatial data
ownership = read_sf(datadir("/raw-data/ownership/S_USA.BasicOwnership.gdb"), "BasicOwnership") 
# plot(fs)

ownership = st_transform(ownership, st_crs(bps_forest))  #set crs equal to bps layer
fs = ownership %>% subset(OWNERCLASSIFICATION == "USDA FOREST SERVICE")

bps_fs_int = st_intersection(bps_forest, fs)

#recalculate area
bps_fs_int$area_int <- as.numeric(st_area(bps_fs_int))

# st_write(bps_fs_int, datadir("/prelim-outputs/BPS/bps_fs_int.shp")) # Writing this doesn't work? "Value 121340700 of field Shap_Ar of feature 3 not successfully written"


#compare fs area to total forest area in reburns
(1-(sum(bps_forest$area) - sum(bps_fs_int$area_int))/sum(bps_forest$area))*100 #81.42% of forested reburned area is in NF land
```


```{r}
# intersect ownership layer with reburns
fs_reburn_int <- st_intersection(reburn_sf, fs_sf)
# plot(reburn_sf$geometry, axes = TRUE)
# plot(fs_reburn_int$geometry) #check if it worked

# sum all forest service land (and remove non FS land)
fs_reburn_area <- fs_reburn_int %>% 
  mutate(area = st_area(.) %>% as.numeric()) %>%
  subset(OWNERCLASSIFICATION == "USDA FOREST SERVICE") %>%
  dplyr::select(c("Fire_Yr", "Fr_Yr_1", "area", "OWNERCLASSIFICATION"))

reburn_sf <- reburn_sf %>% 
  mutate(area = st_area(.) %>% as.numeric()) #add area in m^2

# calcualte percentage of reburn area on FS land ~32 % (7,003,752 hectares)
100 - ((sum(reburn_sf$area) - sum(fs_reburn_area$area))/sum(reburn_sf$area) * 100)


# some summary stats/data vis
fs_reburn_area %>% data.frame() %>%
  group_by(Fire_Yr) %>%
  summarise(acres_yr = sum(area)) %>%
  plot(acres_yr ~ Fire_Yr) 

```
Only ~32% of total reburn area occurred on FS land, but >80% of forest BPS reburn area was on FS land





